### ISSUE TITLE
stop vm not working with the azure pipeline 

### ISSUE THREAD

**Issue by piyushsachdeva2000** [vfabing/AzureVm#15]
Hi,
I have created an Azure DevOps pipeline for start/stop VM using service connection. start task is working fine however, stop task getting failed with the below error:

2020-10-07T17:45:43.4683405Z ##[debug][POST]https://login.windows.net/***/oauth2/token/
2020-10-07T17:45:43.7302725Z ##[debug][POST]https://management.azure.com/subscriptions/xxxxx/resourceGroups/resorucegroupname/providers/Microsoft.Compute/virtualMachines/vmname/powerOff?api-version=2016-03-30
2020-10-07T17:45:43.9428145Z ##[debug]Processed: ##vso[task.logissue type=error;code=AuthorizationFailed;]
2020-10-07T17:45:43.9429619Z ##[debug]task result: Failed
2020-10-07T17:45:43.9430598Z ##[error]Could not stop vmname
2020-10-07T17:45:43.9432145Z ##[debug]Processed: ##vso[task.issue type=error;]Could not stop vmname
2020-10-07T17:45:43.9441902Z ##[debug]Processed: ##vso[task.complete result=Failed;]Could not stop vmname
2020-10-07T17:45:43.9442570Z ##[debug]Stopping-error: [object Object]

Below is the pipeline snippet

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
  name: Azure Pipelines

steps:

- task: AzureVirtualMachineManagerTask@1
  inputs:
    Action: 'Stop VM'
    azureSubscription: 'ServiceConnectionName'
    ResourceGroupName: 'ResourceGroupName'
    VmName: 'VmName'

**Comment by vfabing** [comment]
Hi @piyushsachdeva2000,

Thank you very much for reaching to me !

I just made a quick test with the following yaml pipeline :

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureVirtualMachineManagerTask@1
  inputs:
    Action: 'Stop VM'
    azureSubscription: 'MY AZURE SUBSCRIPTION(57dc3da4-8342-4106-ju41-02a6da83ab0e)'
    ResourceGroupName: 'rg-my-azure-vm-Build'
    VmName: 'vmBuild1'
```

but didn't get any error

![image](https://user-images.githubusercontent.com/14232572/95425426-8d6ba400-0944-11eb-9bc1-5716e665cf9f.png)

> Note: I also tried on the `vs2017-win2016` image, but didn't get any error

What I would try :
- Double check [pipeline permissions](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#pipeline-permissions)?
- Maybe try to create another pipeline with just the `Stop VM` task inside?
- As a workaround, could you try to use [Azure CLI](https://github.com/vfabing/AzureVm/issues/14#issuecomment-620095760) to stop the VM and see if you get the same result?
